### ISSUE TITLE
Reproducing the same Result as Paper

### ISSUE THREAD

**Issue by irfanrah** [wangkaihong/Unsup_Recycle_GAN#19]
Hello, 
I want to try the reproduce the paper's result on Viper2Label.

The setup that I use:
1.
```
python train.py --dataroot ./dataset/viper2label --model unsup_single --dataset_mode unaligned_scale --name v2l_experiment --loadSizeW 286 --loadSizeH 286 --resize_mode rectangle --fineSizeW 256 --fineSizeH 256 --crop_mode rectangle --which_model_netG resnet_6blocks --no_dropout --pool_size 0 --lambda_spa_unsup_A 10 --lambda_spa_unsup_B 0 --lambda_unsup_cycle_A 0 --lambda_unsup_cycle_B 10 --lambda_cycle_A 10 --lambda_cycle_B 10 --lambda_content_A 0 --lambda_content_B 0 --batchSize 1 --noise_level 0.001  --niter_decay 0 --niter 40
```

( I just follow in the readme.md and changing the epochs (niter), because I notice that the maximum 40 epochs will be enough )

2. For the dataset, I copied from RecycleGAN at /Viper/data/cycle-gan
- The Train/A contains 90031 images, its image example in below
![image](https://user-images.githubusercontent.com/20537982/234731065-a8bd80ed-97ba-416a-9595-f6577d9dfee7.png)

- The Train/B contains 90031 images, its image example in below
![image](https://user-images.githubusercontent.com/20537982/234731548-66b57b7c-71c7-4ca6-9399-430b6ac40eb9.png)

Currently, the training at epochs 4 / 70207, and I think the result is won't similar as the paper. Please help me, maybe I do some mistakes. 
![image](https://user-images.githubusercontent.com/20537982/234731751-8305461a-a8e2-4f54-888c-5b53776250b7.png)
![image](https://user-images.githubusercontent.com/20537982/234731787-478353d3-eaef-4e4d-bd37-4cd886e3d428.png)

I think the model was failed in mode collapse, So before canceling the training, I want to ask you opinion and how to reproduce the result. Thanks !

**Comment by wangkaihong** [comment]
This is actually strange. I was wondering if it's possibly related to environmental factors, like pytorch version, as we didn't see many of these issues when we published the work, and reproduction from other users was also successful at that time. Could you please test it with an older version of pytorch and see if it's better? You may try to use the environment Recycle-GAN used, i.e. Pytorch 0.4.

**Comment by irfanrah** [comment]
Sure, I will try that and update this thread later. Thank you for the advice

**Comment by irfanrah** [comment]
Hello @wangkaihong , I have tried several torch version. Currently the better I can made was using torch 1.0.0. and my GPU is RTX 2080 Ti,

However the result is still not as similar as your pre-trained weight, any suggestion ?

![image](https://user-images.githubusercontent.com/20537982/235598287-f048f950-bfea-47d1-bba7-8a54e7e71c56.png)
![image](https://user-images.githubusercontent.com/20537982/235599228-85d7e2e9-6265-4a59-8abb-389c0695590d.png)
